### ISSUE TITLE
`this.path()` not working in Emacs + ESS

### ISSUE THREAD

**Issue by markseeto** [ArcadeAntics/this.path#12]
Thank you for providing the `this.path` package. It looks very useful, but I run R in Emacs + ESS (Emacs Speaks Statistics), and `this.path()` appears to not work when run interactively there.

If I'm in Emacs + ESS and I have a .R file containing
```
library(this.path)

print(this.path())
```

then `this.path()` works correctly if I `source()` the file.

But if I send the code from the .R file to the R console, I get the following error.

```
Error in .this.path.toplevel() : 
  'this.path' used in an inappropriate fashion
* no appropriate source call was found up the calling stack
* R is being run from a shell and argument 'FILE' is missing
```

For comparison, in RGui if I send the same code from the .R file to the R console, it works.

ESS runs R using Rterm.exe.

I'm using this.path 1.4.0, R 4.2.1, ESS 18.10.2, Emacs 27.1, Windows 10.

**Comment by ArcadeAntics** [comment]
Hiya @markseeto !


I've never used Emacs + ESS before so I downloaded it and tried playing around with it. Unfortunately, I found no way to request the path of the opened file. In ESS, it seems as though `ess-load-file` is the function loading the opened file (C-c C-l).
Unfortunately, there is no access to the filename provided to this function, so this will stay unimplemented at least for now. I asked the maintainers of ESS if they would add such a thing to their program, we'll see if they implement such a feature.

Sorry for the lackluster answer, there's just nothing that can be done. In the meantime, you could use Rgui, RStudio, VSCode, or maybe Jupyter.

**Comment by markseeto** [comment]
@ArcadeAntics Thank you for taking the time to investigate this and for making the request to the ESS team.

**Comment by ArcadeAntics** [comment]
Hi again @markseeto !

I've just released a new development version of `package:this.path` which seems to correctly return the path of the R script open in Emacs. This is only a prototype at this point, the implementation may change for the better.

Unfortunately, it only works if Emacs is running as a server (by adding `(server-start)` to your `~/.emacs` file or typing `M-x server-start`) but, at least for now, it was the only way I could implement it.

If you could install it:

```R
install.packages("this.path",
    repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```

and try it out and let me know if it works for you, that'd be wonderful. Thank you!

**Comment by markseeto** [comment]
Hi @ArcadeAntics, thanks for working on this.

I installed the development version using the code you provided above. `sessionInfo()` shows `this.path_2.2.0.4` and R 4.3.1.

I'm not familiar with running Emacs as a server, but I separately tried:
1. Running `M-x server-start`.
2. Adding `(server-start)` to my .emacs file and restarting Emacs.

Both ways, when I sent the following from a .R file to the console
```
library(this.path)
print(this.path())
```
it gave this message:
```
Error in .gui.path() : 
  R is running from a shell and argument 'FILE' is missing
```

**Comment by ArcadeAntics** [comment]
Hi @markseeto ,


It's unfortunate to see it's still not working for you. After typing `M-x server-start` can you try running:

```R
this.path:::.emacs.path()
```

and show me what it outputs? If it works, then I know that determining the R script's path is correct, there's just something wrong with determining the GUI. Could you also run this R code in your Emacs session:

```R
.Platform
commandArgs()
Sys.getpid()
Sys.getenv()
interactive()
```

and show me the output? This will let me know what's wrong with my method of determining the GUI. Thank you!

**Comment by markseeto** [comment]
Hi @ArcadeAntics.

The first time I ran `this.path:::.emacs.path()` gave:
`Error in eval(quote({ : command "emacsclient" not found`

Subsequent times gave:
```
Error in eval(quote({ : command "emacsclient" not found
In addition: Warning message:
In this.path:::.emacs.path() : restarting interrupted promise evaluation
```
```
> .Platform
$OS.type
[1] "windows"

$file.sep
[1] "/"

$dynlib.ext
[1] ".dll"

$GUI
[1] "RTerm"

$endian
[1] "little"

$pkgType
[1] "win.binary"

$path.sep
[1] ";"

$r_arch
[1] "x64"

> commandArgs()
[1] "c:\\Program Files\\R\\R-4.3.1\\bin\\x64\\Rterm.exe"
[2] "--ess"                                             
[3] "--no-save"                                         
> Sys.getpid()
[1] 3424
> Sys.getenv()
ALLUSERSPROFILE           C:\ProgramData
APPDATA                   C:\Users\marks\AppData\Roaming
CommonProgramFiles        C:\Program Files\Common Files
CommonProgramFiles(x86)   C:\Program Files (x86)\Common Files
CommonProgramW6432        C:\Program Files\Common Files
COMPUTERNAME              DESKTOP-UTPMR6V
COMSPEC                   C:\WINDOWS\system32\cmd.exe
CURL_CA_BUNDLE            c:/PROGRA~1/R/R-43~1.1/etc/curl-ca-bundle.crt
DISPLAY                   w32
DriverData                C:\Windows\System32\Drivers\DriverData
EM_PARENT_PROCESS_ID      2600
emacs_dir                 C:/Program Files/GNU Emacs 27.1
HOME                      C:\Users\marks
HOMEDRIVE                 C:
HOMEPATH                  \Users\marks
INSIDE_EMACS              27.1,comint
LOCALAPPDATA              C:\Users\marks\AppData\Local
LOGONSERVER               \\DESKTOP-UTPMR6V
MSYS2_ENV_CONV_EXCL       R_ARCH
NUMBER_OF_PROCESSORS      8
OneDrive                  C:\Users\marks\OneDrive
OneDriveConsumer          C:\Users\marks\OneDrive
OS                        Windows_NT
PAGER                     console
PATH                      c:/rtools43/x86_64-w64-mingw32.static.posix/bin;c:/rtools43/usr/bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\MiKTeX
                          2.9\miktex\bin\x64\;C:\Rtools\bin\;C:\Program
                          Files\Calibre2\;C:\Program
                          Files\dotnet\;C:\Users\marks\AppData\Local\Programs\Python\Python311\;C:\Users\marks\AppData\Local\Programs\Python\Python38-32\;C:\Program
                          Files\lilypond-2.24.1-mingw-x86_64\lilypond-2.24.1\bin;C:\Program
                          Files\Git\cmd;C:\Program Files
                          (x86)\gnupg\bin;C:\Users\marks\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\marks\AppData\Local\Programs\Python\Python311\;C:\Users\marks\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\marks\AppData\Local\Programs\Python\Python38-32\;C:\Users\marks\AppData\Local\Microsoft\WindowsApps;C:\Users\marks\AppData\Local\Pandoc\;C:\Users\marks\AppData\Local\Programs\Microsoft
                          VS Code\bin;
PATHEXT                   .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE    AMD64
PROCESSOR_IDENTIFIER      Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
PROCESSOR_LEVEL           6
PROCESSOR_REVISION        7e05
ProgramData               C:\ProgramData
ProgramFiles              C:\Program Files
ProgramFiles(x86)         C:\Program Files (x86)
ProgramW6432              C:\Program Files
PSModulePath              C:\Program
                          Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                    C:\Users\Public
R_ARCH                    /x64
R_COMPILED_BY             gcc 12.2.0
R_HOME                    c:/PROGRA~1/R/R-43~1.1
R_LIBS_SITE               c:/PROGRA~1/R/R-43~1.1/site-library
R_LIBS_USER               C:\Users\marks\AppData\Local/R/win-library/4.3
R_RTOOLS43_PATH           c:/rtools43/x86_64-w64-mingw32.static.posix/bin;c:/rtools43/usr/bin
R_USER                    C:\Users\marks
RTOOLS40_HOME             C:\rtools40
RTOOLS42_HOME             C:\rtools42
SESSIONNAME               Console
STATATERM                 emacs
SystemDrive               C:
SystemRoot                C:\WINDOWS
TEMP                      C:\Users\marks\AppData\Local\Temp
TERM                      emacs
TERMCAP                   emacs:co#88:tc=unknown:
TMP                       C:\Users\marks\AppData\Local\Temp
USERDOMAIN                DESKTOP-UTPMR6V
USERDOMAIN_ROAMINGPROFILE
                          DESKTOP-UTPMR6V
USERNAME                  seetom
USERPROFILE               C:\Users\marks
windir                    C:\WINDOWS
ZES_ENABLE_SYSMAN         1
> interactive()
[1] TRUE
```

**Comment by ArcadeAntics** [comment]
Hi @markseeto 


I see my mistake now, I assumed `commandArgs()` would always be length 2, something like `c("Rterm.exe", "--ess")`, but yours is `c("Rterm.exe", "--ess", "--no-save")`. I removed the code that checks the length of `commandArgs()`, now it just checks that `"--ess"` is in `commandArgs()`. I think the new version of `package:this.path` should now correctly identify the GUI as Emacs.

As for the error `command "emacsclient" not found`, that's because `emacsclient.exe`, the program used to communicate with the Emacs process, was not found on `PATH` or in the default install location which should be `C:\PROGRA~1\Emacs`. I added some more details to the error messages so now it should tell you why it couldn't find it in the default install location. The simplest way to resolve this is to add the directory of `emacsclient.exe` to PATH. Here is how you can find that directory:

1. press `Windows` key
2. type `Emacs`
3. click `Open file location`
4. right click the Emacs shortcut
5. click `Open file location` (again)
6. copy the directory that appears at the top

If you're unfamiliar with modifying PATH, there are two ways to do it:

1. you can read `?R.from.shell` about how to edit PATH permanently
2. you can add something like `Sys.setenv(PATH = paste0("put directory of emacsclient.exe here, and make sure there is a semicolon at the end of this string;", Sys.getenv("PATH")))` to your `.Rprofile` file

I hope this isn't too confusing, but feel free to ask any questions if that helps. Can you install the newest version `2.2.0.5` and try again? Thank you!

**Comment by markseeto** [comment]
Hi @ArcadeAntics, thanks for working on this.

I installed the development version again and sessionInfo() now says `this.path_2.2.0.5`.

I added `C:\Program Files\GNU Emacs 27.1\bin\` to PATH, using "Edit the system environment variables" in Windows Control Panel. This directory contains emacsclient.exe.

Now when I send `this.path()` to the R console from a .R file in Emacs, it says:
```
Error in .emacs.path(verbose, original, for.msg, contents) : 
  R is running from Emacs with no documents open
```

**Comment by ArcadeAntics** [comment]
Hi @markseeto 


I will modify `.emacs.path()` to be able to recognize `C:\PROGRA~1\GUN Emacs {version}\bin` as a default location for `emacsclient.exe` to be installed. So now it's correctly determining the GUI as Emacs, and it's sending a call correctly, but it's getting `nil` as its return value. Could you run this in Emacs in your R session:

```R
expr <- '
(let ((buffers (reverse (buffer-list)))
      value)
  (while buffers
    (with-current-buffer (car buffers)
      (if (not (string-match-p "^ " (buffer-name)))
          (let ((value0 (list (buffer-name) (buffer-size) major-mode buffer-file-name)))
            (setcdr (nthcdr 3 value0)
              (list
                (let ((process (get-buffer-process (current-buffer))))
                  (if process (process-id process))
                )
              )
            )
            (setq value (cons value0 value))
          )
      )
    )
    (setq buffers (cdr buffers))
  )
  value
)
'
args <- c("emacsclient", "-e", expr)
command <- paste(shQuote(args), collapse = " ")
Sys.getpid()
system(command)
```

and show me the output? It should tell you the buffer name, size, mode, associated filename, and process id for each buffer. I would expect there to be a buffer with the mode `inferior-ess-r-mode` with a process id that matches `Sys.getpid()`, as well as a buffer with the mode `ess-r-mode` with an associated filename. When I run this, I get something like this:

```
> Sys.getpid()
[1] 20548
> system(command)
(("*R*" 2693 inferior-ess-r-mode nil 20548)
 ("test.R" 982 ess-r-mode "c:/Users/iris/AppData/Roaming/Code/test.R" nil)
 ("*Warnings*" 73 special-mode nil nil)
 ("*GNU Emacs*" 796 fundamental-mode nil nil)
 ("*scratch*" 145 lisp-interaction-mode nil nil)
 ("*Messages*" 486 messages-buffer-mode nil nil)
 ("*ESS*" 207 fundamental-mode nil nil)
 ("*Flymake log*" 156 special-mode nil nil))
[1] 0
> 
```

If you do not see that, then hopefully I can make some adjustments to get it working. By the way, I should mention that `package:this.path` does not work if you have multiple Emacs sessions open. This is because emacsclient, by default, interacts with the primary session of Emacs and not any secondary/tertiary/other sessions of Emacs. Unfortunate, but not much I can do about it.

Anyway, let me know what it outputs for you so hopefully I can fix up the mistake. Thank you!

**Comment by markseeto** [comment]
Hi @ArcadeAntics.

```
> Sys.getpid()
[1] 17140
> system(command)
(("thispath01.R" 782 ess-mode "c:/tempwork/thispath01.R" nil)
 ("*GNU Emacs*" 796 fundamental-mode nil nil)
 ("*R*" 1819 inferior-ess-mode nil 17140)
 ("*scratch*" 145 lisp-interaction-mode nil nil)
 ("*Messages*" 652 messages-buffer-mode nil nil)
 ("*ESS*" 6322 fundamental-mode nil nil)
 ("*Flymake log*" 200 special-mode nil nil))
[1] 0
```
I can see that some of my mode names are different from yours. This might be because I have ESS version 18.10.2, which is relatively old. I've tried installing a newer version from MELPA, but it failed to install.

**Comment by ArcadeAntics** [comment]
Hi @markseeto 


I've made the changes so that `"ess-mode"` and `"inferior-ess-mode"` will be recognized along with `"ess-r-mode"` and `"inferior-ess-r-mode"`. If you could please install the newest version of `package:this.path` and try once again and let me know if it works, that'd be wonderful!

Also, I've made the changes so that if `emacsclient.exe` is not on PATH, it will be looked for in `C:/PROGRA~1/GNU Emacs version/bin`. Would you also mind testing that for me? Start a fresh R session in Emacs and run this:

```R
Sys.setenv(PATH = "")
library(this.path)
this.path()
```

And let me know if that works as well. Thank you!

**Comment by markseeto** [comment]
Hi @ArcadeAntics, with this.path 2.2.0.7 it worked, both before and after removing C:\Program Files\GNU Emacs 27.1\bin\ from the path. I also verified that with two instances of Emacs open, it didn't work in the second one, as you said.

Thanks for all the work you've done on this. I'll have to do some reading about what it means to run Emacs as a server, and try it to see whether there are any disadvantages, before deciding whether to continue running Emacs in that way.

**Comment by ArcadeAntics** [comment]
Awesome! Glad to hear it's working! I'll close this issue once the update has made its way to CRAN. If you have any further trouble, just reopen this issue, or start a new issue, either works. Thank you for all your help debugging this, I'm glad to have it resolved!

**Comment by ArcadeAntics** [comment]
Hiya @markseeto!


The update has been released on CRAN. It'll still be a while before the binaries are available there.

There are a couple things I think I should mention.

1. I mentioned that `this.path()` would only work in the primary Emacs session. That is still true. However, if you still want to run multiple R sessions in Emacs, you could instead open one Emacs session with multiple frames, one R session per frame (type `M-x make-frame`). This gives the same appearance as multiple Emacs sessions, except `this.path()` will work in each frame simultaneously, even if the R session is not in the primary frame anymore.
2. You mentioned you wanted to know what running Emacs as a server really means. If you haven't had time to do that, I can explain. It means that the Emacs process is always checking for things to do that could be sent from another program. That's what emacsclient does, let's other programs tell the Emacs session to do something. This has the potential for programs to do something malicious, telling the Emacs process to do something that you don't want it to do. In my case, I'm telling the Emacs process to give the filename of the first R script in its list, something not malicious. Up to you whether you decide to continue running Emacs like that. Unfortunately it is impossible to make `this.path()` work without it. 

If you have any other concerns or questions, just let me know!

Also, if you consider this issue resolved, would you mind closing it? I'd rather the person who opened the issue is also the one to close it. Thank you! 


Regards, 
    Iris

**Comment by markseeto** [comment]
@ArcadeAntics Thank you very much Iris. I hadn't heard of `M-x make-frame` before.
