### ISSUE TITLE
`this.path()` behaves differently inside function in `source()`-ed script

### ISSUE THREAD

**Issue by djvill** [ArcadeAntics/this.path#13]
I'm trying to use `this.path::here()` within a .R script file to make relative paths behave the same way they do in .Rmd files: relative to the script's location. This .R script has a bunch of utility functions for users to use elsewhere (interactively, in other .R/.Rmd files, etc.) But when I source this .R script, there's different behavior depending on whether `here()` is inside a function (likewise for similar functions like `this.path()`)

Reprex using `this.path()`:

`~/a.Rmd`:
````
---
output: md_document
---

```{r}
source("b/utils.R")
myFunc()
```
````

`~/b/utils.R`:
```
library(this.path)
print(this.path(original=TRUE))
myFunc <- function() this.path(original=TRUE)
```

After rendering, here's `~/a.md`:
```
source("b/utils.R")
## [1] "b/utils.R"
myFunc()
## [1] "a.Rmd"
```

Is there an option I'm missing? Or are `here()`/`this.path()`/etc. not meant for this use case?

**Comment by ArcadeAntics** [comment]
Hiya @djvill !


This is something I'm in the middle of fixing for the next major update, hopefully soon.

I feel as though the name `this.path()` implies it will return the path of the document in which it is written. However, it actually returns the path of the executing document, as you've shown here. So, I'd like to rename `this.path()` to `sys.path()` since it nicely matches the **base** functions `sys.call()`, `sys.frame()`, `sys.nframe()`, and `sys.function()`.

However, I don't want to remove `this.path()`, I'd just like to change it's behaviour. My WIP for the update has `this.path()`:

1.  look for a source reference. If it finds one, look for a source file. If it has one, return `filename`.
2.  examine the environment in which it is called. If the top level environment has a `"path"` attribute, then return it.
3. call `sys.path()` as before.

I think something like this would fix your issue. I can upload my progress to GitHub if you'd like to try it. The code works correctly at this point, but it is subject to change and the documentation is rather poor. I'm still trying to flush that out before releasing the update. When it's available, you can install it with:

```R
install.packages("this.path",
    repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```


I would say as a word of caution though, you **MUST** have option `"keep.source"` set to `TRUE`, or else the source references of `~/b/utils.R` will not be stored and `this.path()` will return the wrong path. Additionally, I would like to point out some weird behaviour of how R stores source references.

When R parses some text, it only gives source refences to the top level expressions. That is expressions written at the top level or expressions written inside braces. This means sub-expressions are **NOT** given source references. For example:

file `~/test75.R`:
```R
has.source.reference <- function ()
!is.null(attr(sys.call(), "srcref", exact = TRUE))


fun <- function ()
{
    ## this one will have a source reference
    ## because it is a top level expression
    x <- has.source.reference()
    print(x)
    ## this one will not have a source reference
    ## because it is not a top level expression.
    ## `print()` is the top level expression,
    ## `has.source.reference()` is just a sub-expression
    print(has.source.reference())
    ## this one will have a source reference
    ## because it is a top level expression
    ## (note the surrounding braces)
    print({ has.source.reference() })
    ## this one will have a source reference, weirdly enough.
    ## this is because `return()` and `list()` are not "closure" type functions
    ## they are "special" and "builtin" type functions
    return(list(has.source.reference()))
}
```

and then run it:

```R
source("~/test75.R", keep.source = TRUE)
fun()
```

Basically, R source references are weird. If `this.path()` (or friend) isn't behaving correctly, surround it with braces and try again, it might just fix the issue.

Alternatively, instead of relying on source references, you could modularize your code, that's not too difficult:

```R
## use base namespace instead of base environment for better method dispatch
utils <- new.env(parent = .BaseNamespaceEnv)
## add attribute path so 'this.path()' will find the associated path
attr(utils, "path") <- "~/b/utils.R"
## add a binding '.packageName' so R knows it is a top level environment (see ?topenv)
utils$.packageName <- normalizePath(attr(utils, "path"), "/", TRUE)
## run the code in the environment
sys.source(utils$.packageName, utils)
## this is optional, it just means that bindings cannot be added or
## removed from this environment, and that bindings cannot change value
lockEnvironment(utils, bindings = TRUE)


## and the use it:
utils$myFunc()
```

If there's anything you'd like for me to clarify, just let me know! Thank you!

**Comment by djvill** [comment]
Thanks, this is helpful!

Re: the behavior of future `this.path()`, I think it makes sense to have an argument that controls whether it returns the path of the _calling_ script vs. the _original_ script, with the former being the default so as to not break existing code. That would also allow for a more-informative error message if `this.path()` is used interactively (e.g., `'this.path' used in an inappropriate fashion. Did you want the script where myFunc() was defined (this.path(calling=FALSE))?`)

Re: modularizing, that's a good idea, but it's non-idiomatic for R users.

Re: the source-ref example, does that mean there's a way around this issue that involves adding to `myFunc()` extra braces or `return()`? I tried both and they still return `"a.Rmd"`.

**Comment by djvill** [comment]
Oh, also the hack I'm implementing right now is to just save the output of `this.path()` to a variable in the `source()`-d script, and have functions within that script refer to the variable. It's a somewhat brittle solution because users could accidentally overwrite that variable, and in principle I don't like sourcing non-function variables, but it's at least straightforward.

**Comment by ArcadeAntics** [comment]
I specifically don't want this to be back compatible. I'm planning to make the new version 2.0.0 so that people will know it's not back compatible. I think the current behaviour is misleading and broken.

The source reference example was for the upcoming version. I've uploaded my WIP to github, so if you install it now, you should be able to see it working. If you use `this.path(verbose = TRUE)` you should be able to see the new behaviour, something like:

```R
> this.path(verbose = TRUE)
Source: attr(,"srcref")attr(,"srcfile") of current expression
[1] "C:/Users/iris/Documents/b/utils.R"
```

This should also mean you don't need to save the path in a variable, which I have also thought is undesirable. Hopefully this resolves the issue. If it does, I'd still like to leave this issue open until the documentation is finished and the update is published to CRAN. There will still be some delays because I have to email the maintainers of {ptspotter}, {logr}, {common}, and {neptune} to let them know about these changes, then I might have to wait for them to make changes to their packages,

Let me know if this resolves the issue! And let me know if you find any further bugs from these changes.

**Comment by djvill** [comment]
Aha! This seems to work as expected. Now when I render `a.Rmd` I get

```
source("b/utils.R")
## [1] "b/utils.R"
myFunc()
## [1] "b/utils.R"
```

And it works in my real script too. Thanks for making this change!

I'm going to publish the code that uses the updated `this.dir()`. I hope 2.0.0 can get published to CRAN soon so I can direct readers to a CRAN release!

**Comment by ArcadeAntics** [comment]
Hiya @djvill

Update 2.0.0 was published to CRAN! Would you mind installing from there and confirming it still works as expected?

Also, if this issue is resolved, would you like closing it? I'd rather the one who opened the issue is also the one to close it, thank you!

**Comment by djvill** [comment]
Yes, it's still working in my [code](https://github.com/djvill/SLAC-Fairness). Thanks!

**Comment by ArcadeAntics** [comment]
I have some updates regarding the unusual way in which R stores source references. I previously said that if `this.path()` (or friend) isn't working, surround it with braces and try again. This should no longer be necessary with the newest development version, just write your code like normal and this.path will work. I plan to publish this version to CRAN by the start of the next week.
