### ISSUE TITLE
this.dir(), here() etc. result in "Error: RStudio not running" in VSCode

### ISSUE THREAD

**Issue by rambles** [ArcadeAntics/this.path#14]
Hello

Many of the key functions in this.path now return 'Error: RStudio not running' when running code interactively in VSCode:-

```r
R version 4.2.3 (2023-03-15 ucrt) -- "Shortstop Beagle"
Platform: x86_64-w64-mingw32 (64-bit)
r$>source(this.path::path.join(this.path::this.dir(), "__Project_Standards.r"))
Error: RStudio not running
r$> this.path::here()
Error: RStudio not running
r$> this.path::this.dir()
Error: RStudio not running
```

I'm using the latest release of VScode, and it's just possible it's then where the problem started (it previously worked fine before).  I can't be sure however as I installed the R terminal for VSCode ('Radian') at the same time, and it could be *that* that's causing the issue.  That said, I did try using the standard terminal, rterm.exe, and the problem remained.

I should add too that this.path still works very well in RStudio (same this.path installation).  I'm running the latest this.path from Github.

Thanks for a great package by the way!

**Comment by ArcadeAntics** [comment]
Hiya @rambles

As far as I know, **this.path** should work in VSCode, with or without the radian console. However, it's been a while since I tried.

To diagnose this issue, can you run the following for me?:

```R
interactive()
Sys.getenv("TERM_PROGRAM")
this.path:::.shINFO
.Platform
commandArgs()
```

Also, something else to check. Normally, VSCode starts an R session and attaches some variables and gets "RStudio" running. Sometimes it fails to attach and you get this error. If you look in the bottom bar, you should see the current version of R running, something like

R: 4.3.1

If VSCode failed to attach the variables, it should look like this instead

R: (not attached)

If so, you should be able to click it like a button and it should reattempt to attach, then **this.path** should be working.

Finally, one suggestion. You can rewrite the first line much shorter:

```R
source(this.path::here("__Project_Standards.r"))
```

Thank you!

**Comment by rambles** [comment]
Hi  

Thanks for the quick response!

Here're the results from running the code you asked for:-

```r
[1] TRUE    
[1] "vscode"
$ENC        
[1] NA

$no.echo
[1] NA

$FILE
[1] NA

$EXPR
[1] NA

$has.input
[1] NA

$OS.type
[1] "windows"

$file.sep
[1] "/"

$dynlib.ext
[1] ".dll"

$GUI
[1] "RTerm"

$endian
[1] "little"

$pkgType
[1] "win.binary"

$path.sep
[1] ";"

$r_arch
[1] "x64"

[1] "radian"               "--quiet"              "--no-restore-history" "--no-save"
[5] "--no-restore-data"
``` 

I checked if R was attached - and it wasn't! - but attaching it hasn't affected this.path working I'm afraid.

And I've noted your improved code.  Thanks for that.

**Comment by ArcadeAntics** [comment]
Hi again!


All of the results from running the code look good to me.

I feel like I had this problem a while back so I went digging again through the setup and recommendations for the R Extension for VSCode. It seems like they recommend the following be placed in your site-wide startup profile file or your user profile (see `?Startup`):

```R
options(vsc.rstudioapi = TRUE)
```

this means `rstudioapi::getSourceEditorContext()` works as intended which means `this.path()` works as intended.  They have some other recommendations too:

```R
options(
    vsc.rstudioapi = TRUE,
    vsc.use_httpgd = TRUE,
    languageserver.server_capabilities = list(
        signatureHelpProvider = list(triggerCharacters = list("(", ",", "$")),
        completionProvider = list(
            resolveProvider = TRUE,
            triggerCharacters = list(".", ":", "$")
        )
    )
)
```

but supposedly only the first is needed. If that works, I might update **this.path** to include something like:

```R
    failure <- tryCatch({
        context <- rstudioapi::getSourceEditorContext()
        FALSE
    }, error = function(e) TRUE)
    if (failure)
        stop("package {rstudioapi} is not set up to work with VSCode, try adding:\n\n```R\noptions(vsc.rstudioapi = TRUE)\n```\n\nto your site-wide startup profile file or your user profile (see ?Startup for more),\nthen restart your R session and try again")
```

so that other people in your situation can more easily resolve the issue.

Also, if you don't like the colour scheme of your radian console, you change it like this:

```R
options(radian.color_scheme = "monokai")  ## or whatever scheme looks good
```

again in your site-write startup profile file or your user profile.

I'm not entirely sure this will resolve your issue, it sounds like it was working before but now it's not. If you installed a new version of VSCode, it's possible that `options(vsc.rstudioapi = TRUE)` was the default before, but now it's not and must be specifically set by the user.


Thank you!

**Comment by rambles** [comment]
Hi

Brilliant!  It was the RStudio setting you first described.  It was off and after switching it on again, this.path started working as before.

Thanks again for looking into this.  I could have sworn I'd already set this but in all honesty, I've been messing with the settings quite a bit recently, so I might well have switched it off again.  Who knows?  It's easy to lose in VSCode, there's so much twiddling one can do!

Thanks again for your help with this (and for creating such a great package!)

Cheers

**Comment by ArcadeAntics** [comment]
Hiya @rambles!


Glad to hear it's working as before! I published an update to CRAN which, in the described scenario, will throw an error with a more informative message, so I think this is resolved now. If you also consider this resolved, can you close this issue? I'd rather the creator of the issue is also the one to close it.


Thank you!
    Iris

**Comment by rambles** [comment]
No problem, happy to do it.  Thanks again for your work on the package!

Cheers, Rich
