### ISSUE TITLE
Use `package:this.path` in Power BI?

### ISSUE THREAD

**Issue by leechaowen** [ArcadeAntics/this.path#16]
by the way, is possible load this package when using power-bi? 

https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals

**Comment by ArcadeAntics** [comment]
Hiya @leechaowen 


From what I tested today, it does not seem to be possible to use `this.path()` inside a Power BI script. However, implementing `this.path()` to work in Power BI seems to go against its intentions. It wants you to load the data you need in Power BI, which it will then automatically transfer to the R session for you to use. You should not need the path of the script because all of your data should already be imported. And it seems like all of the output data is already retrieved and put into the Power BI report. So the R script should never need to interact with the file system, Power BI is doing all that work for you already.

If you have any other questions, just let me know.

**Comment by leechaowen** [comment]
yes, you are right. I import the data into power-bi first then create visual by R. Thanks.
